version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: nestuser
      PMA_PASSWORD: nestpass
    ports:
      - "8080:80"
    depends_on:
      - mysql
  
  smtp:
    image: bytemark/smtp
    container_name: smtp-local
    restart: always
    ports:
      - "25:25"
    environment:
      RELAY_HOST: smtp.example.com
      RELAY_PORT: 587
      RELAY_USERNAME: smtp
      RELAY_PASSWORD: secret
